default: &default
adapter: postgresql
encoding: unicode
pool: 5
username: username
password: password

development:
< database: app_development

test:
< database: app_test

production:
< database: app_production